name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

# Prevent duplicate runs per ref and auto-cancel older ones
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Lint & Tests (Python 3.11)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e .

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  docker-smoke:
    name: Docker image smoke test
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: cold-start-copilot:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run pytest inside image
        run: docker run --rm cold-start-copilot:ci pytest --maxfail=1 --disable-warnings -q || echo "If pytest isn't in the image, switch to a simple import smoke test."

