# .github/workflows/test.yml
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1) Get code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # 3) Install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest

      # 4) Install your package (src layout)
      - name: Install package
        run: pip install -e .

      # 5) Run tests
      - name: Run tests
        env: 
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q
